package com.empman.dto;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Employee Data Transfer Object (DTO)
 * 
 * Used for API requests and responses. Decouples the API contract from the internal
 * entity model, enabling API versioning and security benefits.
 * 
 * For API Requests (Add/Update):
 * - name: Employee name (required)
 * - email: Employee email (required, valid format)
 * - department: Department name (required)
 * - salary: Employee salary (required, positive)
 * 
 * For API Responses:
 * - All fields above plus:
 * - id: Employee ID
 * - createdAt: Creation timestamp
 * - updatedAt: Last update timestamp
 * 
 * Validation Annotations:
 * - @NotBlank: Field must not be empty or whitespace-only
 * - @Email: Field must be a valid email format
 * - @Positive: Numeric field must be positive
 * - @NotNull: Field must not be null
 * 
 * @since 1.0.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EmployeeDTO {

    /**
     * Employee ID (only in responses, not in requests).
     * Auto-generated by the system.
     */
    private Long id;

    /**
     * Employee name (required, max 255 characters).
     * Must not be empty or contain only whitespace.
     */
    @NotBlank(message = "Name is required and cannot be empty")
    @Size(min = 1, max = 255, message = "Name must be between 1 and 255 characters")
    private String name;

    /**
     * Employee email (required, unique, valid email format, max 255 characters).
     * Must follow standard email format (e.g., user@domain.com).
     */
    @NotBlank(message = "Email is required and cannot be empty")
    @Email(message = "Email must be a valid email address")
    @Size(min = 1, max = 255, message = "Email must be between 1 and 255 characters")
    private String email;

    /**
     * Employee department (required, max 255 characters).
     * Must not be empty or contain only whitespace.
     */
    @NotBlank(message = "Department is required and cannot be empty")
    @Size(min = 1, max = 255, message = "Department must be between 1 and 255 characters")
    private String department;

    /**
     * Employee salary (required, positive decimal).
     * Must be a positive value with precision up to 19 digits and 2 decimal places.
     * Examples: 50000.00, 75000.50, 100000.99
     */
    @NotNull(message = "Salary is required")
    @Positive(message = "Salary must be a positive value greater than zero")
    @DecimalMin(value = "0.01", message = "Salary must be at least 0.01")
    @Digits(integer = 17, fraction = 2, message = "Salary must have at most 17 integer digits and 2 decimal places")
    private BigDecimal salary;

    /**
     * Timestamp when the employee was created (only in responses).
     * Set automatically by the system when the employee is created.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp when the employee was last updated (only in responses).
     * Updated automatically by the system whenever the employee record is modified.
     */
    private LocalDateTime updatedAt;

    /**
     * String representation of the EmployeeDTO.
     * Format: EmployeeDTO(id, name, email, department, salary)
     * 
     * @return String representation
     */
    @Override
    public String toString() {
        return "EmployeeDTO{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", department='" + department + '\'' +
                ", salary=" + salary +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }

}
